version: '2'

services:

  {% if docker_port_forward.postgis is defined %}

  postgis:
    ports:
      # - "6543:5432"
      {% if docker_port_forward.postgis.postgis is defined %}

      - "{{ docker_port_forward.postgis.postgis }}:5432"

      {% endif %}
  {% endif %}

  qgis-server:
    environment:
      - DEBUG={{ qgis_server.DEBUG }}
      - QGIS_LOG_FILE={{ qgis_server.QGIS_LOG_FILE }}
      - QGIS_SERVER_LOG_FILE={{ qgis_server.QGIS_SERVER_LOG_FILE }}
      # Log level 0 is the lowest (catch all), 5 is the highest (only fatal error)
      - QGIS_DEBUG={{ qgis_server.QGIS_DEBUG }}
      - QGIS_SERVER_LOG_LEVEL={{ qgis_server.QGIS_SERVER_LOG_LEVEL }}
      # It is important to include this environment variable
      # QGIS-Server:LTR cgi needs it
      - QGIS_PROJECT_FILE=
    {% if docker_port_forward.qgis_server is defined %}

    ports:
      # - "9003:80"
      {% if docker_port_forward.qgis_server.http is defined %}

      - "{{ docker_port_forward.qgis_server.http }}:80"

      {% endif %}
    {% endif %}

  django:
    # Loading the app is defined here to allow for
    # autoreload on changes it is mounted on top of the
    # old copy that docker added when creating the image
    volumes:
      - '../src/geonode:/usr/src/app'
      - './pycharm_helpers/django:/root/.pycharm_helpers'
    environment:
      - DEBUG={{ django.DEBUG }}
      - SITEURL={{ django.SITEURL }}
      - GEONODE_BASE_URL={{ django.GEONODE_BASE_URL }}
      - QGIS_SERVER_URL={{ django.QGIS_SERVER_URL }}
      - GEOSERVER_BASE_URL={{ django.GEOSERVER_BASE_URL }}
    {% if django.command is defined %}

    command: {{ django.command }}

    {% endif %}
    {% if docker_port_forward.django is defined %}

    ports:
      # - "9000:22"
      {% if docker_port_forward.django.ssh is defined %}

      - "{{ docker_port_forward.django.ssh }}:22"

      {% endif %}
    {% endif %}

  {% if docker_port_forward.nginx is defined %}

  nginx:
    ports:
      # - "80:80"
      {% if docker_port_forward.nginx.http is defined %}

      - "{{ docker_port_forward.nginx.http }}:80"

      {% endif %}
  {% endif %}

  {% if docker_port_forward.web is defined %}

  web:
    ports:
      # - "80:80"
      {% if docker_port_forward.web.http is defined %}

      - "{{ docker_port_forward.web.http }}:80"

      {% endif %}
  {% endif %}

  celery:
    # Loading the app is defined here to allow for
    # autoreload on changes it is mounted on top of the
    # old copy that docker added when creating the image
    volumes:
      - '../src/geonode:/usr/src/app'
      - './pycharm_helpers/celery:/root/.pycharm_helpers'
    environment:
      - DEBUG={{ celery.DEBUG }}
    {% if celery.command is defined %}

    command: {{ celery.command }}

    {% endif %}
    {% if docker_port_forward.celery is defined %}

    ports:
      # - "9001:22"
      {% if docker_port_forward.celery.ssh is defined %}
      - "{{ docker_port_forward.celery.ssh }}:22"
      {% endif %}
    {% endif %}

  inasafe-headless:
    environment:
      - INASAFE_HEADLESS_DEPLOY_OUTPUT_DIR={{ inasafe_headless.INASAFE_HEADLESS_DEPLOY_OUTPUT_DIR }}
      - INASAFE_HEADLESS_DEPLOY_OUTPUT_URL={{ inasafe_headless.INASAFE_HEADLESS_DEPLOY_OUTPUT_URL }}
      - QGIS_LOG_FILE={{ inasafe_headless.QGIS_LOG_FILE }}
      - QGIS_DEBUG_FILE={{ inasafe_headless.QGIS_DEBUG_FILE }}
      - QGIS_DEBUG={{ inasafe_headless.QGIS_DEBUG }}
      - INASAFE_WORK_DIR={{ inasafe_headless.INASAFE_WORK_DIR }}
    volumes:
      - './pycharm_helpers/inasafe-headless:/root/.pycharm_helpers'
    {% if inasafe_headless.command is defined %}

    command: {{ inasafe_headless.command }}

    {% endif %}
    {% if docker_port_forward.inasafe_headless is defined %}

    ports:
      # - "9002:22"
      {% if docker_port_forward.inasafe_headless.ssh is defined %}

      - "{{ docker_port_forward.inasafe_headless.ssh }}:22"

      {% endif %}
    {% endif %}

  inasafe-headless-analysis:
    environment:
      - INASAFE_HEADLESS_DEPLOY_OUTPUT_DIR={{ inasafe_headless_analysis.INASAFE_HEADLESS_DEPLOY_OUTPUT_DIR }}
      - INASAFE_HEADLESS_DEPLOY_OUTPUT_URL={{ inasafe_headless_analysis.INASAFE_HEADLESS_DEPLOY_OUTPUT_URL }}
      - QGIS_LOG_FILE={{ inasafe_headless_analysis.QGIS_LOG_FILE }}
      - QGIS_DEBUG_FILE={{ inasafe_headless_analysis.QGIS_DEBUG_FILE }}
      - QGIS_DEBUG={{ inasafe_headless_analysis.QGIS_DEBUG }}
      - INASAFE_WORK_DIR={{ inasafe_headless_analysis.INASAFE_WORK_DIR }}
    volumes:
      - './pycharm_helpers/inasafe-headless-analysis:/root/.pycharm_helpers'
    {% if inasafe_headless_analysis.command is defined %}

    command: {{ inasafe_headless_analysis.command }}

    {% endif %}
    {% if docker_port_forward.inasafe_headless_analysis is defined %}

    ports:
      # - "9002:22"
      {% if docker_port_forward.inasafe_headless_analysis.ssh is defined %}

      - "{{ docker_port_forward.inasafe_headless_analysis.ssh }}:22"

      {% endif %}
    {% endif %}
