version: '2'

services:

  qgis-server:
    ports:
      - "9003:80"

  django:
    # Loading the app is defined here to allow for
    # autoreload on changes it is mounted on top of the
    # old copy that docker added when creating the image
    volumes:
      - '../src/geonode:/usr/src/app'
    environment:
      - DEBUG=True
    command: /setup-geonode.sh dev
    ports:
      - "9000:22"

  celery:
    # Loading the app is defined here to allow for
    # autoreload on changes it is mounted on top of the
    # old copy that docker added when creating the image
    volumes:
      - '../src/geonode:/usr/src/app'
    environment:
      - DEBUG=True
    command: /setup-geonode.sh dev
    ports:
      - "9001:22"

  inasafe-headless:
    command: /start-celery.sh dev
    ports:
      - "9002:22"