version: '2'
services:

  postgres:
    volumes:
      - './pg/postgres_data/data:/var/lib/postgresql/data'

  qgis-server:
    build: docker-qgis-server
    volumes:
      - '../src/geonode:/usr/src/app'
      - '../src/core:/usr/src/core'
      - '../src/geosafe:/usr/src/geosafe'
      - '../src/geonode_qgis_server/geonode_qgis_server:/usr/src/geonode_qgis_server'
      - '../src/otf-project:/opt/qgis-server/plugins/otf-project'
    command:
      - /setup-qgis-server.sh
    environment:
      - DEBUG=False

  django:
    build: docker-geonode
#    image: geonode_django
    volumes:
      - '../src/geonode:/usr/src/app'
      - '../src/core:/usr/src/core'
      - '../src/geosafe:/usr/src/geosafe'
      - '../src/geonode_qgis_server/geonode_qgis_server:/usr/src/geonode_qgis_server'
      - '../src/otf-project:/opt/qgis-server/plugins'
#    command: django-admin.py runserver 0.0.0.0:8000
    command: /setup-geonode.sh
    environment:
      - DEBUG=False
      - PYTHONPATH=/usr/src:/usr/src/app/
      - DJANGO_SETTINGS_MODULE=core.settings
      - ROOT_URLCONF=core.urls
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - SITEURL=http://localhost/
      - GEONODE_BASE_URL=http://nginx/
      - QGIS_SERVER_URL=http://qgis-server/cgi-bin/qgis_mapserv.fcgi
    links:
      - inasafe-output
      - qgis-server
    ports:
      - "81:80"

  celery:
    build: docker-geonode
#    image: geonode_django
    working_dir: /usr/src/app
    volumes:
      - '../src/geonode:/usr/src/app'
      - '../src/core:/usr/src/core'
      - '../src/geosafe:/usr/src/geosafe'
      - '../src/geonode_qgis_server/geonode_qgis_server:/usr/src/geonode_qgis_server'
    environment:
      - DEBUG=False
      - PYTHONPATH=/usr/src:/usr/src/app/
      - DJANGO_SETTINGS_MODULE=core.settings
      - ROOT_URLCONF=core.urls
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - SITEURL=http://localhost/
      - GEONODE_BASE_URL=http://nginx/
      - QGIS_SERVER_URL=http://qgis-server/cgi-bin/qgis_mapserv.fcgi
    command: celery -A geosafe worker -l info -Q default,cleanup,email,update,geosafe -n geonode.%h -B
    links:
      - inasafe-output
      - qgis-server

  inasafe-output:
    image: nginx
    volumes:
      - ./inasafe/headless/output:/usr/share/nginx/html/output
    ports:
      - "8081:80"

  inasafe-headless:
    build: docker-inasafe-headless
    volumes:
      - '../src/inasafe:/home/src/inasafe'
      - './inasafe/headless/output:/home/output'
    working_dir: /home/src/inasafe
    environment:
      - C_FORCE_ROOT=True
      - PYTHONPATH=/home/src/inasafe
      - DISPLAY=:99
      - INASAFE_HEADLESS_BROKER_HOST=amqp://guest:guest@rabbitmq:5672/
      - INASAFE_HEADLESS_DEPLOY_OUTPUT_DIR=/home/output/
      - INASAFE_HEADLESS_DEPLOY_OUTPUT_URL=http://inasafe-output/output/
    command: /start-celery.sh
    links:
      - rabbitmq:rabbitmq
