---
- name: customize geosafe celeryconfig
  template:
    src: geosafe-tasks-headless-celeryconfig.py
    dest: '{{ project_path }}/src/geosafe/tasks/headless/celeryconfig.py'
    owner: '{{ remote_user }}'
    group: '{{ remote_group }}'
    mode: "u=rw,g=rw,o=r"
